// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.duyminh.grpc;

public interface APIReponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:APIReponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responsemessage = 1;</code>
   */
  java.lang.String getResponsemessage();
  /**
   * <code>string responsemessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponsemessageBytes();

  /**
   * <code>bool status = 2;</code>
   */
  boolean getStatus();
}
